# Файл конфигурации модели динамики ЛА (коэффициенты для аппарата parrot mini)

# Шаг интегрирования симулятора (сек)
simulationStep: 0.01
# Время симуляции
simulationTotalTime: 1000
# Коефициент рефльного времени
realTimeFactor: 1
# Масса аппарата (кг)
mass: 0.0630
# Коэффициент тяги двигателей
motorThrustCoef: 3.9865e-08 # 3.13e-5
# Коэфициент сопротивления при вращении ротора
motorResistCoef: 7.5e-7
#  длина лучей мультикоптера
lengthOfFlyerArms: 0.17
# Количество роторов
numberOfRotors: 4
# Диагональные элементы тензора инерции(осевые моменты инерции)
Ixx: 5.82857e-04 #0.0686e-3
Iyy: 7.16914e-04 #0.092e-3
Izz: 0.01 #0.1366e-3
# Ограничение по скорости вращения роторов(радиан/секунда)
maxVelocityRotors: 2631
minVelocityRotors: 0
